<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "cm_losungen"
 *
 * Auto generated by Extension Builder 2013-11-24
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Losungen',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Jannes Dinse, Sebastian Tobies',
	'author_email' => 'jdinse@codemaschine.de, stobies@codemaschine.de',
	'author_company' => 'CODE MASCHINE GbR, CODE MASCHINE GbR',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>